// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: chittychat/chittychat.proto

package chittychat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageControllerClient is the client API for MessageController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageControllerClient interface {
	SendMessage(ctx context.Context, in *MessagePost, opts ...grpc.CallOption) (*MessagePostReply, error)
}

type messageControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageControllerClient(cc grpc.ClientConnInterface) MessageControllerClient {
	return &messageControllerClient{cc}
}

func (c *messageControllerClient) SendMessage(ctx context.Context, in *MessagePost, opts ...grpc.CallOption) (*MessagePostReply, error) {
	out := new(MessagePostReply)
	err := c.cc.Invoke(ctx, "/chittychat.MessageController/sendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageControllerServer is the server API for MessageController service.
// All implementations must embed UnimplementedMessageControllerServer
// for forward compatibility
type MessageControllerServer interface {
	SendMessage(context.Context, *MessagePost) (*MessagePostReply, error)
	mustEmbedUnimplementedMessageControllerServer()
}

// UnimplementedMessageControllerServer must be embedded to have forward compatible implementations.
type UnimplementedMessageControllerServer struct {
}

func (UnimplementedMessageControllerServer) SendMessage(context.Context, *MessagePost) (*MessagePostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageControllerServer) mustEmbedUnimplementedMessageControllerServer() {}

// UnsafeMessageControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageControllerServer will
// result in compilation errors.
type UnsafeMessageControllerServer interface {
	mustEmbedUnimplementedMessageControllerServer()
}

func RegisterMessageControllerServer(s grpc.ServiceRegistrar, srv MessageControllerServer) {
	s.RegisterService(&MessageController_ServiceDesc, srv)
}

func _MessageController_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageControllerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chittychat.MessageController/sendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageControllerServer).SendMessage(ctx, req.(*MessagePost))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageController_ServiceDesc is the grpc.ServiceDesc for MessageController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chittychat.MessageController",
	HandlerType: (*MessageControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendMessage",
			Handler:    _MessageController_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chittychat/chittychat.proto",
}
